name: Build/push image and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .editorconfig
      - .gitignore
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - id: build
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Google Cloud authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          region: ${{ secrets.GCP_REGION }}
          env_vars: ${{ secrets.GCP_ENV_VARS }}
          image: gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE }}:latest@sha256${{ needs.build.outputs.digest }}
          service: ${{ ecrets.GCP_SERVICE }}
