name: Build and push image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - run.sh
      - oauth2-proxy.cfg

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - id: build
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE }}:latest
