name: Deploy to Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Google Cloud authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          region: ${{ secrets.GCP_REGION }}
          env_vars: ${{ secrets.GCP_ENV_VARS }}
          image: gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE }}:latest
          service: ${{ secrets.GCP_SERVICE }}
